baseURL = 'https://printf-scanf.pages.dev/'
languageCode = 'en-us'
title = 'Printf/Scanf'
theme = "mini"

paginate = 2
[permalinks]
  posts = "/posts/:title/"
[params]
 colortheme = "dark"
 favicon = "fav.png"    
 enablerss = true
 author = "Shashank Shekhar"
 bio = "Techincal blogs and life stories by Shashank Shekhar"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[social]
  github = 'https://github.com/thatShashankGuy/'   
  linkedin = 'https://www.linkedin.com/in/thatshashanguy/'

  
