baseURL = 'https://blog.shashankshekhar.in/'
languageCode = 'en-us'
title = 'Blogs | Shashank Shekhar'


paginate = 3

[params]
 externals = 'References'
 colortheme = "dark"
 favicon = "fav.png"    
 enableRSS = true
 author = "Shashank Shekhar"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[social]
  github = 'https://github.com/thatShashankGuy/'   
  linkedin = 'https://www.linkedin.com/in/thatshashanguy/'
  email = 'mailto:shashankforworkshekhar@gmail.com' 

  
